# Generated by Django 4.2.7 on 2023-11-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('original_url', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('short_url', models.CharField(max_length=500, unique=True)),
                ('click_clount', models.IntegerField(default=0)),
            ],
        ),
    ]
