# Generated by Django 4.2.7 on 2023-11-06 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='click_clount',
            new_name='click_count',
        ),
    ]
